metadata:
  game_name: Cyberpunk 2077
  version: '1.0'
  created_with: Katana Workflow Builder
  created_date: '2025-12-09 06:26:22'
  path: C:\Program Files (x86)\Steam\steamapps\common\Cyberpunk 2077\bin\x64\Cyberpunk2077.exe
  process_id: Cyberpunk2077
  process_name: Cyberpunk2077.exe
  benchmark_name: Cyberpunk ingame benchmark
  benchmark_duration: 90
  startup_wait: 90
  resolution: 1920x1080
  preset: High
  engine: CD Projekt Red
  graphics_api: DirectX 11
steps:
  1:
    description: NAVIGAE TO MAIN MENU - SPACE
    find:
      type: icon
      text: ''
      text_match: contains
    action:
      type: key
      key: space
    expected_delay: 2
    timeout: 20
  2:
    description: NAVIGATE TO SETTINGS
    find:
      type: any
      text: SETTINGS
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.1
      click_delay: 0.3
    expected_delay: 2
    timeout: 20
  3:
    description: NAVIGATE TO GRAPHICS MENU
    find:
      type: icon
      text: ''
      text_match: contains
    action:
      type: key
      key: '3'
    expected_delay: 2
    timeout: 20
  4:
    description: NAVIGATE TO GRAPHICS MENU 2
    find:
      type: icon
      text: ''
      text_match: contains
    action:
      type: key
      key: '3'
    expected_delay: 2
    timeout: 20
  5:
    description: NAVIGATE TO GRAPHICS MENU 3
    find:
      type: icon
      text: ''
      text_match: contains
    action:
      type: key
      key: '3'
    expected_delay: 2
    timeout: 20
  6:
    description: SELECT RUN BENCHMARK OPTION
    find:
      type: icon
      text: ''
      text_match: contains
    action:
      type: key
      key: b
    expected_delay: 3
    timeout: 20
  7:
    description: CONFIRM TO RUN BENCHMARK
    find:
      type: icon
      text: ''
      text_match: contains
    action:
      type: key
      key: enter
    expected_delay: 2
    timeout: 20
  8:
    description: WAIT FOR BENCHMARK TO COMPLETE
    action:
      type: wait
      duration: 100
    expected_delay: 3
    timeout: 20
  9:
    description: 'HIT EXIT TO MAIN MENU '
    find:
      type: icon
      text: ''
      text_match: contains
    action:
      type: key
      key: esc
    expected_delay: 2
    timeout: 20
  10:
    description: CONFIRM EXIT TO MAIN MENU
    find:
      type: icon
      text: ''
      text_match: contains
    action:
      type: key
      key: enter
    expected_delay: 20
    timeout: 20
  11:
    description: NAVIGAE TO MAIN MENU - SPACE
    find:
      type: icon
      text: ''
      text_match: contains
    action:
      type: key
      key: space
    expected_delay: 3
    timeout: 20
  12:
    description: NAVIGATE TO QUIT GAME
    find:
      type: any
      text: QUIT
      text_match: contains
    action:
      type: click
      button: left
      move_duration: 0.3
      click_delay: 0.2
    expected_delay: 3
    timeout: 20
fallbacks:
  general:
    action: key
    key: escape
    expected_delay: 1
